# Generated by Django 4.2.4 on 2023-08-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='street',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
