# Generated by Django 4.2.4 on 2023-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_userinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='card_cvv',
            field=models.CharField(default='000', max_length=4),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='card_number',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='exp_month',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='exp_year',
            field=models.CharField(default='2023', max_length=4),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='payment_method',
            field=models.CharField(default='credit_card', max_length=20),
        ),
    ]
