# Generated by Django 4.2.4 on 2023-08-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_userinformation_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='exp_month',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='exp_year',
        ),
    ]
