# Generated by Django 4.2.4 on 2023-08-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_userinformation_card_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='payment_method',
        ),
    ]
