# Generated by Django 4.2.4 on 2023-08-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_userinformation_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='product',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
