# Generated by Django 4.1.7 on 2023-08-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_userinformation_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='phone_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='zipcode',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
