# Generated by Django 4.1.7 on 2023-08-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_userinformation_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='product',
        ),
    ]
