# Generated by Django 4.1.7 on 2023-08-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_userinformation_cart_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='cart_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cartitem'),
        ),
    ]
