# Generated by Django 4.1.7 on 2023-08-09 23:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0012_userinformation_cart_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInformation',
            new_name='UserInfo',
        ),
    ]
