# Generated by Django 4.1.7 on 2023-08-10 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_userinformation_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.userinfo'),
        ),
    ]
