# Generated by Django 4.1.7 on 2023-08-10 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_cartitem_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='user_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.userinfo'),
        ),
    ]
