# Generated by Django 4.1.7 on 2023-08-10 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_cartitem_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user_info',
        ),
    ]
