# Generated by Django 4.1.7 on 2023-08-10 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_cartitem_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal')], max_length=20)),
                ('card_number', models.CharField(max_length=16, verbose_name='Credit Card Number')),
                ('card_cvv', models.CharField(max_length=4, verbose_name='Card CVV')),
                ('exp_month', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, verbose_name='Expiration Month')),
                ('exp_year', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4, verbose_name='Expiration Year')),
                ('userinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.userinfo')),
            ],
        ),
    ]
