# Generated by Django 4.1.7 on 2023-08-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='userinfo',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
