# Generated by Django 4.2.4 on 2023-08-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_payment_userinfo_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_code',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
