# Generated by Django 4.2.4 on 2023-08-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='forget_password_token',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
